!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 8
  - - clip_range
    - 0.4
  - - ent_coef
    - 2.931484907646462e-05
  - - gae_lambda
    - 1.0
  - - gamma
    - 0.9
  - - learning_rate
    - 0.0001271857047377097
  - - max_grad_norm
    - 5
  - - n_envs
    - 3
  - - n_epochs
    - 20
  - - n_steps
    - 128
  - - n_timesteps
    - 10000000.0
  - - policy
    - MultiInputPolicy
  - - policy_kwargs
    - dict( activation_fn=nn.ReLU, net_arch=[dict(pi=[64, 64], vf=[64, 64])] )
  - - vf_coef
    - 0.06252372815378887
